---
# vars file for roles/manageDNServer

#configuracion zonas
zoneDomain:
  -  aag.com.mx
  -  aagelectronica.com
  -  amtelser.com
  -  cpv3.com
  -  encontrack.com
  -  flotaencontrol.com
  -  flotcon.com
  -  instalacionmexico.com
  -  5.190.10.in-addr.arpa
  -  6.190.10.in-addr.arpa

serialZone: 2020051204

subDomain: 
  - encontrack.com

#Configuracion name.conf

masterserver: '10.190.5.90; 127.0.0.1;'
slaveserver: '10.10.4.32; 127.0.0.1;'
#slaveserver: '10.190.4.32; 127.0.0.1;'
master: '10.190.5.90;'
slaves: '10.10.4.32; 10.190.4.32;'
acls: '127.0.0.1;
        10.190.4.32;
        192.168.4.79;
        10.190.0.0/23;
        10.190.3.0/24;
        10.190.4.0/23;
        10.190.6.0/24;
        10.190.10.0/24;
        10.10.0.0/21;
        10.10.8.0/21;
        172.16.0.0/20;
        172.31.0.0/16;
        192.168.0.0/16;'
